export const WORLD_CURRENCIES: {
    name: string,
    countryName: string,
    countryCode: string,
    currencyCode: string
}[] = [
    {
        name: "US Dollar",
        countryName: "United States",
        countryCode: "US",
        currencyCode: "USD",
    },
    {
        name: "Euro",
        countryName: "Eurozone",
        countryCode: "EU",
        currencyCode: "EUR",
    },
    {
        name: "Pound Sterling",
        countryName: "United Kingdom",
        countryCode: "UK",
        currencyCode: "GBP",
    },
    {
        name: "Japanese Yen",
        countryName: "Japan",
        countryCode: "JP",
        currencyCode: "JPY",
    },
    {
        name: "Swiss Franc",
        countryName: "Switzerland",
        countryCode: "CH",
        currencyCode: "CHF",
    },
    {
        name: "Canadian Dollar",
        countryName: "Canada",
        countryCode: "CA",
        currencyCode: "CAD",
    },
    {
        name: "Australian Dollar",
        countryName: "Australia",
        countryCode: "AU",
        currencyCode: "AUD",
    },
    {
        name: "New Zealand Dollar",
        countryName: "New Zealand",
        countryCode: "NZ",
        currencyCode: "NZD",
    },
    {
        name: "Chinese Yuan",
        countryName: "China",
        countryCode: "CN",
        currencyCode: "CNY",
    },
    {
        name: "Indian Rupee",
        countryName: "India",
        countryCode: "IN",
        currencyCode: "INR",
    },
    {
        name: "Brazilian Real",
        countryName: "Brazil",
        countryCode: "BR",
        currencyCode: "BRL",
    },
    {
        name: "Russian Ruble",
        countryName: "Russia",
        countryCode: "RU",
        currencyCode: "RUB",
    },
    {
        name: "South African Rand",
        countryName: "South Africa",
        countryCode: "ZA",
        currencyCode: "ZAR",
    },
    {
        name: "Mexican Peso",
        countryName: "Mexico",
        countryCode: "MX",
        currencyCode: "MXN",
    },
    {
        name: "South Korean Won",
        countryName: "South Korea",
        countryCode: "KR",
        currencyCode: "KRW",
    },
    {
        name: "Argentine Peso",
        countryName: "Argentina",
        countryCode: "AR",
        currencyCode: "ARS",
    },
    {
        name: "Bolivian Boliviano",
        countryName: "Bolivia",
        countryCode: "BO",
        currencyCode: "BOB",
    },
    {
        name: "Chilean Peso",
        countryName: "Chile",
        countryCode: "CL",
        currencyCode: "CLP",
    },
    {
        name: "Colombian Peso",
        countryName: "Colombia",
        countryCode: "CO",
        currencyCode: "COP",
    },
    {
        name: "Ecuadorian Sucre",
        countryName: "Ecuador",
        countryCode: "EC",
        currencyCode: "ECS",
    },
    {
        name: "Guyanese Dollar",
        countryName: "Guyana",
        countryCode: "GY",
        currencyCode: "GYD",
    },
    {
        name: "Paraguayan Guarani",
        countryName: "Paraguay",
        countryCode: "PY",
        currencyCode: "PYG",
    },
    {
        name: "Peruvian Sol",
        countryName: "Peru",
        countryCode: "PE",
        currencyCode: "PEN",
    },
    {
        name: "Surinamese Dollar",
        countryName: "Suriname",
        countryCode: "SR",
        currencyCode: "SRD",
    },
    {
        name: "Uruguayan Peso",
        countryName: "Uruguay",
        countryCode: "UY",
        currencyCode: "UYU",
    },
    {
        name: "Venezuelan Bolivar",
        countryName: "Venezuela",
        countryCode: "VE",
        currencyCode: "VES",
    },
];